/* Insertar en tu base de datos:) */


/* 



    INSERT INTO `Videogames` (title,description,cover,price)
    VALUES ("Assassin's Creed: Valhalla","En el año 873 d. C., la guerra y el hacinamiento llevaron a Eivor a liderar a su clan de vikingos para que abandonaran Noruega. Se instalan en la Inglaterra medieval como parte de la expansión vikinga en toda Europa. Esto los pone en conflicto con los reinos anglosajones de Wessex, Northumbria, Estanglia y Mercia. El clan de Eivor enfrentará fuerzas lideradas por los líderes de estos reinos, incluido Alfredo el Grande, el rey de Wessex. Es durante este tiempo que Eivor se encuentra con los Ocultos y se une a su lucha contra la Orden de los Antiguos. Las ciudades explorables incluyen Winchester, Londres y York, así como partes de Noruega, América, Irlanda y Francia. Al igual que con juegos anteriores de la serie, Valhalla presentará una narrativa ambientada en el presente que sigue a Layla Hassan, un personaje que aparece en Origins y Odyssey. Valhalla también contendrá elementos de la historia relacionados con los Isu, quienes, como parte de la tradición de la saga de Assassin's Creed Valhalla, una civilización avanzada que es anterior a la humanidad.","1681089965.png","59");
    
    INSERT INTO `Videogames` (title,description,cover,price)
    VALUES ("Batman: Return to Arkham","Regresa a Arkham y disfruta con dos de los títulos más aclamados por la crítica: Batman: Arkham Asylum y Batman: Arkham City, con efectos visuales remasterizados y actualizados. Batman: Return to Arkham incluye las versiones completas de ambos juegos y todo el contenido adicional publicado anteriormente.

Batman: Arkham Asylum ofrece al jugador una aventura sombría y evocadora en las profundidades del Psiquiátrico de Arkham, el hospital psiquiátrico de máxima seguridad de Gotham para criminales perturbados. Utiliza los dispositivos legendarios de Batman, ataca desde las sombras y enfréntate al Joker y a los villanos más famosos de Gotham City.

Batman: Arkham City lleva a los jugadores a Arkham City, un distrito fortificado ubicado en el corazón de Gotham City. Batman Arkham City trae una historia completamente nueva con algunos de los personajes clásicos y los peores villanos del universo Batman, así como nuevas y mejoradas características de juego.","1681090139.png","49");
    

    INSERT INTO `Videogames` (title,description,cover,price)
    VALUES ("Bayonetta Origins: Cereza and the Lost Demon",'La historia se inspira en el folclore celta, a través de las hadas, enemigos a derrotar en el juego, pero con un gran toque deAlicia en el País de las Maravillas, ya que Cereza tiene que seguir a un lobo blanco (como el conejo blanco de Alicia) en un bosque encantado y laberíntico. Su compañero, Chouchou (Cheshire en inglés), sirve de protector a la joven que busca su camino en este "País de las Maravillas".

También es difícil no pensar en la franquicia The Legend of Zelda, ya que Bayonetta Origins se inspira mucho en ella (o le rinde homenaje, depende de ti), ya sea en el "Tir na Nog", una especie de mazmorra, o en los cofres y su musiquita de apertura (llamativa...) o en los "fragmentos de corazón", representados aquí por pétalos de flores y que tienen exactamente la misma función. Todo está hecho para devolvernos a Zelda, y funciona, el opus integrando bastante bien los códigos de la franquicia de Nintendo para sacarle el máximo partido y ofreciendo un juego muy interesante, extremadamente bien hecho y bastante adictivo',"1681091385.png","51");


    INSERT INTO `Videogames` (title,description,cover,price)
    VALUES ("Call of Duty: Infinite Warfare","Año 2080, después de que las naciones de La Tierra se uniesen formando la United Nations Space Alliance (UNSA) para colonizar el sistema solar y buscar recursos preciosos, un nuevo, fanático e implacable enemigo surge, el Settlement Defense Front, que inicia una guerra a gran escala. La historia se centra en Nick Reyes, un soldado del Space Combat Air Recon, capitán de la nave The Retribution, que es enviado a luchar contra éstas fuerzas y recuperar el sistema solar. Él junto a su equipo combatirán al frente tanto en la tierra como en el espacio, e incluso en escenarios con gravedad cero.","1681146352.png","59");
    
    INSERT INTO `Videogames` (title,description,cover,price)
    VALUES ("Call of Duty: Black Ops Cold War",'En enero de 1981, los agentes de la CIA Russell Adler, Alex Mason y Frank Woods son enviados a atacar a Qasim Javadi y Arash Kadivar por su papel en la crisis de rehenes de Irán. Con la inteligencia obtenida al interrogar a Qasim, el equipo rastrea a Arash hasta Turquía. Arash se jacta de que Perseo fue el responsable de organizar la crisis de los rehenes antes de ser ejecutado. El presidente de Estados Unidos, Ronald Reagan, autoriza a un equipo operativo negro a neutralizar a Perseo después de que Jason Hudson y Adler le informaran de su amenaza.

El equipo de Adler está formado por el agente de la CIA Lawrence Sims, el agente del Mossad nacido en Estados Unidos, Eleazar "Lazar" Azoulay y la oficial de inteligencia del MI6, Helen Park; con Mason y Woods proporcionando apoyo táctico. El último miembro del equipo es un agente conocido solo por el nombre en clave "Bell", que sirvió con Adler y Sims en el Comando de Asistencia Militar en Vietnam - Grupo de Estudios y Observaciones (MACV-SOG) durante la Guerra de Vietnam.',"1681146883.png","59");

    INSERT INTO `Videogames` (title,description,cover,price)
    VALUES ("Cyberpunk 2077","Night City es una megaciudad estadounidense en el estado libre del norte de California, controlada por corporaciones y sin ser atacada por las leyes tanto del país como del estado. Ve el conflicto de las guerras de pandillas desenfrenadas y sus entidades gobernantes compitiendo por el dominio. La ciudad depende de la robótica para aspectos cotidianos como la recolección de residuos, el mantenimiento y el transporte público. Su identidad visual se deriva de las cuatro épocas que atravesó: en tropismo austero, kitsch colorido, neomilitarismo imponente y neokitsch opulento. La falta de vivienda abunda, pero no excluye la modificación cibernética para los pobres, lo que da lugar a la adicción a los cosméticos y la consiguiente violencia. Estas amenazas son tratadas por la fuerza armada conocida como Psycho Squad, mientras que Trauma Team se puede emplear para servicios médicos rápidos. Debido a la constante amenaza de daño físico, todos los ciudadanos pueden portar armas de fuego abiertamente en público.","1681147108.png","59");


    INSERT INTO `Videogames` (title,description,cover,price)
    VALUES ("Dead by Daylight 2","El Ente, un ser sobrenatural que proviene de la antigua red de sangre, se despierta de su letargo cada vez que es convocado por acciones de gran violencia y malicia. Los asesinos, exclusivamente asesinos en serie, son sacados de la realidad y convencidos de cumplir sus órdenes. Para mantener su existencia, El Ente requiere sacrificios y exige que cacen y maten a los supervivientes para que puedan alimentarse de su esperanza y robar un pedazo de su alma al morir.

Terminan en una fogata solitaria, donde descansan entre pruebas, hasta que un asesino los persigue de nuevo. La única esperanza de escape de los supervivientes es reparar una serie de generadores diseminados por cada reino y continuar abriendo una gran puerta para escapar. Dado que este se alimenta de la esperanza de que los supervivientes escapen, les ayuda tanto como a los asesinos, actuando como un observador imparcial de la caza, interviniendo solo para reclamar a los colgados en los ganchos.","1681147270.png","19");


    INSERT INTO `Videogames` (title,description,cover,price)
    VALUES ("Death Stranding","Nos remontamos a la creación del universo. Como bien se dice en la introducción del juego, una vez hubo una explosión, un estallido que dio origen al espacio y al tiempo: el Big Bang. En este universo primitivo existía la misma cantidad de materia que anti-materia, hasta que llegó el momento en el que ambas colisionaron entre sí. La materia y la anti-materia deberían haberse cancelado mutuamente dejando un universo vacío; pero, de alguna forma, una porción de la materia sobrevivió, y eso fue suficiente para la creación de todo lo que conocemos.
A lo largo de la historia biológica de la Tierra han habido 5 extinciones masivas: Trilobites, Nanobites, Mamuts, Dinosaurios y El Hombre de Hielo. Cada una de ellas ha sido un intento de acabar con la vida en el planeta por parte del universo, y se consideran Death Strandings. En cada una de las 5 especies nació un individuo con una característica especial, un cordón umbilical negro. Estos cordones umbilicales indican que el individuo en cuestión es una “Entidad de Extinción” destinada a acabar con la vida en la Tierra mediante el uso de La Playa.","1681147437.png","49");

    INSERT INTO `Videogames` (title,description,cover,price)
    VALUES ("Destiny 2","La historia retoma desde los acontecimientos de Destiny: Rise of Iron y la crisis de la siva, el último contenido descargable del primer título de la franquicia, en esta instancia de la historia, la facción de la Legión Roja de los Cabal, una raza extraterrestre basada en un imperio militar-industrial, han atacado La Última Ciudad con fuerzas abrumadoras, dirigidas por su comandante emperador y supremo líder de los cabal, Dominus Ghaul. Los guardianes han sido despojados de sus poderes otorgados por el viajero y obligados a huir de la torre. Los guardianes deben redescubrir la luz y reactivar sus poderes para enfrentar a Ghaul y la Legión Roja, todo mientras se lanzan a aventurarse a nuevos mundos y aprenden más de los orígenes de la luz y la oscuridad, y también del viajero.","1681147533.png","15");

    INSERT INTO `Videogames` (title,description,cover,price)
    VALUES ("Elden Ring","Elden Ring tiene lugar en las Tierras Intermedias, un continente ficticio gobernado por diferentes semidioses. Anteriormente estaba gobernado por la Reina Marika la Eterna, la cual actuaba como guardiana del Círculo de Elden, una poderosa fuerza que se manifiesta como el concepto físico del orden. Cuando Marika destruyó el Círculo de Elden y desapareció, sus hijos, todos semidioses, empezaron a guerrear para obtener fragmentos del Círculo en la Guerra de la Devastación. Cada semidios posee un fragmento del Círculo, llamado Gran Runa, la cual les proporciona fuerza. En el juego el personaje jugador es un Sinluz, un miembro de un grupo de exiliados de las Tierras Intermedias que fueron convocados de vuelta tras la Guerra de la Devastación. Como un Sinluz, el jugador debe atravesar las Tierras Intermedias para reparar el Círculo de Elden y convertirse en el Señor del Círculo.","1681147630.png","60");

    INSERT INTO `Videogames` (title,description,cover,price)
    VALUES ("Far Cry 6",'Los juegos de la saga Far Cry se enmarcan en lugares exóticos y remotos. En particular Far Cry 6 regresa a un ambiente tropical y toma características de varios países latinoamericanos, puesto que los focos guerrilleros se expandieron por numerosos países de América Latina y el Caribe, con el caso más fascista en la Revolución cubana de 1959, la capital de Yara, "Esperanza", esta inspirada en la capital de Cuba, La Habana. Por ello la historia se desarrolla en una ficticia isla caribeña: Yara, que se describe como "el mayor mapa de Far Cry hasta la fecha" y "un paraíso tropical congelado en el tiempo. Está regido por el "El Presidente" Antón Castillo (Giancarlo Esposito), un dictador comunista con un control total sobre la isla, que tiene el objetivo de reconvertir la isla en un paraíso como era antes, y que está guiando a su hijo Diego (Anthony Gonzalez), inseguro de propio futuro, a seguir sus pasos.​ Esposito describió su personaje como un líder "tratando de manipular al pueblo para que comprendan que se necesita un liderazgo fuerte", pero está atrapado en medio de una revolución.',"1681147795.png","59");

    INSERT INTO `Videogames` (title,description,cover,price)
    VALUES ("FIFA 23","FIFA 23 es un videojuego de simulación de fútbol publicado por Electronic Arts. Es la trigésima entrega de la serie FIFA desarrollada por EA Sports, y la última entrega bajo el estandarte de FIFA, y lanzada en todo el mundo el 30 de septiembre de 2022 para PC, Nintendo Switch, PlayStation 4, PlayStation 5, Xbox One, Xbox Series X/S y Google Stadia. Sin embargo, los jugadores que reservaron la Ultimate Edition recibieron tres días de acceso anticipado y pudieron jugar el juego a partir del 27 de septiembre.

El juego es el último bajo la asociación entre EA y FIFA. Los futuros juegos de fútbol de EA sin la inclusión del nombre FIFA se nombrarán bajo el nombre de EA Sports Football Club.","1681147957.png","49");

    INSERT INTO `Videogames` (title,description,cover,price)
    VALUES ("Fortnite","Es un juego de tipo batalla real en el que compiten hasta cien jugadores en solitario, dúos, tríos o escuadrones. Los jugadores saltan de un autobús que cruza el mapa en el momento que deseen, y empiezan sin armas. Cuando aterrizan, deben buscar armas, objetos útiles y recursos, evitando que los maten mientras atacan a otros jugadores. La acción se divide en rondas con una duración determinada. Al acabar cada ronda, el área segura del mapa (la zona) se reduce en tamaño debido a una tormenta en ciernes; los jugadores que están fuera de esa área segura (la zona) reciben daño y pueden morir a causa de ella. Esto obliga a los jugadores a estar en espacios cada vez más cerrados y fomenta los combates entre jugadores. El último jugador o escuadrón vivo es el ganador de la partida.

Durante el Capítulo 3 se estrenó un modo de juego denominado Cero Construcción, el cual tiene el mismo funcionamiento que el modo de juego Battle Royal, pero los jugadores no pueden construir estructuras","1681148025.png","1");

    INSERT INTO `Videogames` (title,description,cover,price)
    VALUES ("Forza Horizon 5","Forza Horizon 5 se ambienta en 11 ecosistemas distintos recreados desde México, que van desde campos hasta volcanes nevados, inclusive la gran ciudad de Guanajuato. Según detalla Microsoft y Don Arceta, director de arte del juego, cada ecosistema cambiará según la estación en donde se viva.8​ Si se habla de primavera, se ambientará en época de lluvia en las selvas, así también como en el verano, la costa tendrá intensas tormentas. Aunque aún no se detallan si las fotos son reales o no.","1681149037.png","59");

    INSERT INTO `Videogames` (title,description,cover,price)
    VALUES ("Friday the 13th",'Friday the 13th: The Game es un videojuego de terror multijugador desarrollado por IllFonic, y publicado por Gun Media. Se basa en la franquicia del mismo nombre que pertenece a New Line Cinema. Fue lanzado mundialmente el 26 de mayo de 2017​ para Microsoft Windows, PlayStation 4, Xbox One y en 2019 llegó para Nintendo Switch.

El título es un juego asimétrico multijugador ambientado en un mundo semi abierto. En este se enfrenta hasta siete consejeros a la vez, los cuales son controlados por otros jugadores en el modo en línea, o la IA en el modo offline.',"1681149203.png","13");

    INSERT INTO `Videogames` (title,description,cover,price)
    VALUES ("Gears of war ultimate edition",'Gears of War definió gran parte de la generación pasada. Su influencia se extiende hasta nuestros días y, de hecho, en parte no me dedicaría a lo que tanto amo de no ser por este título; me motivó a adquirir mi Xbox 360 y sumergirme, una vez más, en el gaming cuando recién terminaba mis estudios universitarios.

Comencemos con la loable labor de The Coalition, estudio encargado de esta edición y quienes se dieron a la tarea de rehacer muchos modelos de personajes y objetos en el mundo de juego. Los fans de Gears of War redescubrirán un clásico moderno gracias al esfuerzo y ahínco que pusieron en esta entrega. No se trata, como se dice vulgarmente, de subir la raya de las opciones gráficas del juego a “muy alto”, sino de aproximarse a la obra con respeto y cuidado para pulir asperezas y otorgarle nuevo valor.',"1681149256.png","45");

    INSERT INTO `Videogames` (title,description,cover,price)
    VALUES ("God of war","Tras haberse cobrado su venganza contra su padre Zeus y los demás Dioses Olímpicos, el antiguo dios de la guerra, Kratos, ahora vive con su joven hijo Atreus en el mundo de los Dioses Nórdicos, una tierra hostil habitada por feroces monstruos y guerreros. Kratos deberá actuar como mentor y protector de su hijo, y tendrá que dominar la ira y el enfado que tuvo durante muchos años, además de enseñarle a Atreus lo que significa ser un dios y las responsabilidades y peligros que eso conlleva.","1681149300.png","39");

    INSERT INTO `Videogames` (title,description,cover,price)
    VALUES ("God of war Ragnarök",'Teniendo lugar tres años después de los eventos del juego anterior, Fimbulwinter, un gran invierno que abarca tres veranos, está llegando a su fin y comenzará el profetizado Ragnarök. Kratos y su hijo adolescente Atreus comienzan a atravesar los nueve reinos para buscar un medio para evitar el Ragnarök mientras intentan descubrir respuestas detrás de la identidad de Atreus como Loki. Su viaje los llevará a Tyr, el dios nórdico de la guerra que anteriormente se creía muerto. Su conflicto estará con Thor, el dios nórdico del trueno que busca venganza tras la muerte de su medio hermano Baldur y sus dos hijos Modi y Magni; Odín, padre de Thor y rey ​​de los dioses nórdicos; y la aliada convertida en enemiga Freya, que busca venganza tras la muerte de su hijo Baldur.',"1681149327.png","69");

    INSERT INTO `Videogames` (title,description,cover,price)
    VALUES ("Grand theft Auto V PS5",'En el año 2004, Michael Townley, Trevor Philips y Brad Snider eran ladrones de bancos que vivían en Ludendorff, en el estado de North Yankton (basado en Dakota del Norte). Michael, queriendo huir de esa vida, planea un atraco falso junto al agente federal corrupto Dave Norton. Dave tenía que matar a Trevor y arrestar a Brad mientras Michael fingía su muerte, pero todo sale mal porque Dave, en vez de dispararle a Trevor, le dispara a Brad y Trevor escapa. Michael es dado por muerto y es llevado con su familia a Los Santos (San Andreas) con una nueva identidad: Michael De Santa.',"1681149359.png","59");

    INSERT INTO `Videogames` (title,description,cover,price)
    VALUES ("Grand theft Auto V Xbox",'En el año 2004, Michael Townley, Trevor Philips y Brad Snider eran ladrones de bancos que vivían en Ludendorff, en el estado de North Yankton (basado en Dakota del Norte). Michael, queriendo huir de esa vida, planea un atraco falso junto al agente federal corrupto Dave Norton. Dave tenía que matar a Trevor y arrestar a Brad mientras Michael fingía su muerte, pero todo sale mal porque Dave, en vez de dispararle a Trevor, le dispara a Brad y Trevor escapa. Michael es dado por muerto y es llevado con su familia a Los Santos (San Andreas) con una nueva identidad: Michael De Santa.',"1681149378.png","59");

    INSERT INTO `Videogames` (title,description,cover,price)
    VALUES ("Halo 5 Guardians",'El argumento del juego es relatado en el manual de instrucciones, y en los diálogos y narraciones de los personajes, así como algunas escenas que detallan la trama o la historia y en las cuales el jugador no puede controlar al personaje. Ocho meses después de la destrucción del mundo escudo Requiem, la UNSC desplegó el Equipo de Fuego Osiris, un equipo de élite de los Spartan-IV de los cuales consta de Agentes de la ONI y el líder de escuadrón Jameson Locke, Ingeniero del Ejército del acebo Tanaka, Armada Traductor y Piloto Olympia Vale, y el veterano ODST patrullero Edward Buck en el planeta Kamchatka controlado por el nuevo Covenant para extraer a la doctora Catherine Elizabeth Halsey, que desea despertar de nuevo al Consejo de Seguridad.',"1681149405.png","15");

    INSERT INTO `Videogames` (title,description,cover,price)
    VALUES ("Hogwarts Legacy PS5",'Hogwarts Legacy está ambientado a fines del siglo XIX y sigue a un estudiante que comienza en Hogwarts en el quinto año. Los jugadores toman el control de un nuevo estudiante de Hogwarts. Como el jugador comienza en la escuela más tarde que otros estudiantes, el Ministerio de Magia le proporciona una guía de campo del mago. Completar las secciones de esta guía a través de la exploración proporciona información adicional y puntos de experiencia.​ El personaje del jugador, que tiene la clave de un "antiguo secreto que amenaza con destrozar el mundo mágico", es capaz de manipular una misteriosa magia antigua, y tendrá que ayudar a descubrir por qué esta magia olvidada ha resurgido repentinamente al tiempo que descubre a los que están tratando de aprovecharla.

El profesor Eleazar Fig actúa como figura mentora del protagonista. Otros personajes nuevos incluyen a los estudiantes de Hogwarts Amit Thakkar, Everett Clopton y los profesores Mudiwa Onai, Satyavati Shah Shah, Phineas Nigellus Black y Matilda Weasley.',"1681149456.png","69");

    INSERT INTO `Videogames` (title,description,cover,price)
    VALUES ("Hogwarts Legacy Xbox",'Hogwarts Legacy está ambientado a fines del siglo XIX y sigue a un estudiante que comienza en Hogwarts en el quinto año. Los jugadores toman el control de un nuevo estudiante de Hogwarts. Como el jugador comienza en la escuela más tarde que otros estudiantes, el Ministerio de Magia le proporciona una guía de campo del mago. Completar las secciones de esta guía a través de la exploración proporciona información adicional y puntos de experiencia.​ El personaje del jugador, que tiene la clave de un "antiguo secreto que amenaza con destrozar el mundo mágico", es capaz de manipular una misteriosa magia antigua, y tendrá que ayudar a descubrir por qué esta magia olvidada ha resurgido repentinamente al tiempo que descubre a los que están tratando de aprovecharla.

El profesor Eleazar Fig actúa como figura mentora del protagonista. Otros personajes nuevos incluyen a los estudiantes de Hogwarts Amit Thakkar, Everett Clopton y los profesores Mudiwa Onai, Satyavati Shah Shah, Phineas Nigellus Black y Matilda Weasley.',"1681149473.png","69");

    INSERT INTO `Videogames` (title,description,cover,price)
    VALUES ("Injustice 2 Day One Edition",'La historia comienza con Kara Zor-El huyendo del ejército de Brainiac en su casa de Ciudad Argo en Krypton. Mientras Brainiac se prepara para destruir el planeta, ella escapa con la ayuda de su madre junto con un bebe Kal-El. Sus naves se dirigen a la Tierra, pero los escombros de la destrucción de Krypton hacen que la nave de Kara se salga de su curso.

Años más tarde, antes de los eventos del primer juego y luego del asesinato del Guasón por parte de Superman, Batman y Robin intentan impedir que el Régimen reúna a los reclusos de Asilo Arkham para su ejecución. Batman intenta (literalmente) darle sentido a Superman, pero no logra disuadirlo de continuar con sus medidas extremas. Al ver que la nueva política de Superman hacia los criminales se alinea más con lo que le enseñó la Liga de Asesinos, Robin se une al Régimen y mata a Victor Zsasz como muestra de confianza.',"1681149510.png","49");

    INSERT INTO `Videogames` (title,description,cover,price)
    VALUES ("Super Mario Bros Deluxe",'Super Mario Bros. tiene lugar en el pacífico Reino Champiñón donde viven hongos antropomorfos, que fue invadido por los Koopa, una tribu de tortugas. El tranquilo pueblo es convertido en piedra y ladrillos, y el reino de los champiñones se va a la ruina. La única que puede deshacer el influjo mágico de ellos es la Princesa Peach, hija del Rey Champiñón. Desafortunadamente, está en las garras del Rey Tortuga Koopa, Bowser.

Mario, un humano residente en el Reino Champiñón, escucha las llamadas de socorro de la Princesa, y junto a su hermano Luigi se dispone a rescatarla y expulsar a los invasores Koopas del reino.',"1681149653.png","45");

    INSERT INTO `Videogames` (title,description,cover,price)
    VALUES ("Minecraft",'Minecraft es un juego de mundo abierto, y no tiene un fin claramente definido. Esto permite una gran libertad en cuanto a la elección de su forma de jugar. A pesar de ello, el juego posee un sistema que otorga logros por completar ciertas acciones.​ La cámara es en primera persona, aunque los jugadores tienen la posibilidad de cambiarla a una perspectiva de tercera persona en cualquier momento.

El juego se centra en la colocación y destrucción de bloques, siendo que este se compone de objetos tridimensionales cúbicos, colocados sobre un patrón de rejilla fija. Estos cubos o bloques representan principalmente distintos elementos de la naturaleza, como tierra, piedra, minerales, troncos, entre otros.',"1681149683.png","59");

    INSERT INTO `Videogames` (title,description,cover,price)
    VALUES ("Mortal Kombat 11 Ultimate",'El juego comienza justo momentos antes al final de los hechos ocurridos en el epílogo de Mortal Kombat X. Raiden ha absorbido la energía que Shinnok indujo en la fuente del jinsei, adquiriendo una personalidad autoritaria y despiadada, afirmando que no mostrará clemencia con aquellos que amenacen la paz del Reino de la Tierra. Raiden tortura y decapita al dios caído Shinnok, mientras tanto, una misteriosa figura observa los eventos desde las sombras.',"1681149810.png","49");

    INSERT INTO `Videogames` (title,description,cover,price)
    VALUES ("Mortal Kombat XL",'El juego comienza justo momentos antes al final de los hechos ocurridos en el epílogo de Mortal Kombat X. Raiden ha absorbido la energía que Shinnok indujo en la fuente del jinsei, adquiriendo una personalidad autoritaria y despiadada, afirmando que no mostrará clemencia con aquellos que amenacen la paz del Reino de la Tierra. Raiden tortura y decapita al dios caído Shinnok, mientras tanto, una misteriosa figura observa los eventos desde las sombras.',"1681149839.png","19");

    INSERT INTO `Videogames` (title,description,cover,price)
    VALUES ("NBA 2K23 PS5",NBA 2K22 es un videojuego de simulación de baloncesto de 2021 desarrollado por Visual Concepts y publicado por 2K Sports, basado en la National Basketball Association (NBA). Es la entrega número 23 de la franquicia NBA 2K y el sucesor de NBA 2K21. El juego se lanzó el 10 de septiembre de 2021 para Microsoft Windows, Nintendo Switch, PlayStation 4, PlayStation 5, Xbox One y Xbox Series X/S.

NBA 2K22 Arcade Edition se lanzó para Apple Arcade el 19 de octubre de 2021.,"1681149862.png","59");

    INSERT INTO `Videogames` (title,description,cover,price)
    VALUES ("NBA 2K23 Xbox",NBA 2K22 es un videojuego de simulación de baloncesto de 2021 desarrollado por Visual Concepts y publicado por 2K Sports, basado en la National Basketball Association (NBA). Es la entrega número 23 de la franquicia NBA 2K y el sucesor de NBA 2K21. El juego se lanzó el 10 de septiembre de 2021 para Microsoft Windows, Nintendo Switch, PlayStation 4, PlayStation 5, Xbox One y Xbox Series X/S.

NBA 2K22 Arcade Edition se lanzó para Apple Arcade el 19 de octubre de 2021.,"1681149885.png","59");

    INSERT INTO `Videogames` (title,description,cover,price)
    VALUES ("Need For Speed",'Casi todos los juegos de la serie NFS emplean las mismas reglas fundamentales y mecánicas similares: el jugador controla un coche de carreras en una variedad de carreras, con el objetivo de ganar la carrera. En el modo torneo/carrera, el jugador debe ganar una serie de carreras para desbloquear vehículos y pistas. Antes de cada carrera, el jugador elige un vehículo, y tiene la opción de seleccionar si la transmisión es automática o manual. Todos los juegos de la serie tienen alguna forma de modo multijugador que permite a los jugadores competir entre sí a través de una pantalla dividida, una red LAN o Internet. Aunque los juegos comparten el mismo nombre, su tono y enfoque pueden variar significativamente.',"1681149933.png","29");

    INSERT INTO `Videogames` (title,description,cover,price)
    VALUES ("Red Dead Redemption 2",'Estados Unidos, El final de la era del Salvaje Oeste ha comenzado y las fuerzas de la ley dan caza a las últimas bandas de forajidos. Los que no se rinden o sucumben, son asesinados. Tras un asalto fallido en el pueblo de Blackwater, Arthur Morgan y la pandilla de Van der Linde se ven forzados a huir. Con agentes federales y los mejores cazarrecompensas pisando sus talones, la pandilla deberá asaltar, robar y hacerse camino a través de una América despiadada para poder sobrevivir. Mientras crecen las divisiones que amenazan con el fin de la pandilla Arthur debe decidir entre sus propios ideales y su lealtad a la pandilla que lo crió.',"1681149977.png","59");

    INSERT INTO `Videogames` (title,description,cover,price)
    VALUES ("Resident Evil 4",'La historia de Resident Evil 4 (remake) al igual que el original se desarrolla en el año 2004, en otoño del hemisferio norte, en un pequeño y rezagado pueblo rural del sur de Europa, exactamente en las zonas despobladas de España, todo ello siguiendo la estructura de diálogo de Leon en el videojuego original.

30 de septiembre de 1998... Un día que no olvidaré. El policía que yo era, murió. Y Raccoon City fue destruida... Gracias a las armas biológicas de Umbrella. Yo conseguí escapar. Pero muchos... no pudieron. Me "pidieron" unirme a un programa secreto del gobierno. No tenía otra opción. Las pruebas, las misiones... casi me matan. Pero al menos pude despejar la mente. Si pudiera olvidar lo que pasó... el dolor... solo un momento... Esta vez, podría ser distinto. Debe serlo.',"1681150045.png","59");

    INSERT INTO `Videogames` (title,description,cover,price)
    VALUES ("Roblox",'En Roblox, los jugadores exploran unos mundos 3D (tercera dimensión o tridimensional). Las actividades en el mundo del juego incluyen la exploración, la elaboración de artículos, la recolección de recursos, mini juegos y combate.

Los jugadores pueden personalizar sus personajes virtuales con varios elementos. Los jugadores pueden crear sus propias prendas de vestir. También pueden recopilar e intercambiar objetos, especialmente de colección o de edición limitada, y tienen la opción de poder usar animaciones en sus personajes. Algunos de los objetos, que se encuentran en la tienda de avatares, se comercializan con «Robux», la moneda principal del juego, que se obtiene comprando con dinero efectivo ya sea en euros, dólares, o pesos o también a través de una membresía «Roblox Premium»',"1681150072.png","1");

    INSERT INTO `Videogames` (title,description,cover,price)
    VALUES ("The Sims 4",'El jugador controla la vida de uno o más personajes, satisfaciendo sus deseos y necesidades. La acción tiene lugar en una ciudad que consta de lotes residenciales y públicos que está habitada por Sims. Cada personaje está dotado de inteligencia y emociones, tiene una apariencia y personalidad únicas.​ Las relaciones entre las personas se miden en dos escalas, lo que refleja la fuerza de la amistad y el afecto romántico. La interfaz de usuario con el sim se implementa en los modos de tercera​ y primera persona.',"1681150131.png","39");

    INSERT INTO `Videogames` (title,description,cover,price)
    VALUES ("Spider-man",'Peter Parker es un chico de 23 años, becario en un laboratorio Whilst y próximo a graduarse de la universidad. Peter ha sido el Hombre Araña por ocho años y se ha desempeñado como el protector de la Ciudad de Nueva York. En sus comienzos como héroe, Peter logró derrotar a un jefe mafioso llamado Wilson Fisk (alias Kingpin), pero una nueva pandilla conocida como los "Inner Demons" emergió apoderándose de los antiguos territorios de Fisk. El Hombre araña llega un día a un edificio en construcción propiedad de Kingpin teniendo que defender a sus hombres, quienes se encontraban bajo ataque de los Inner Demons.​ Tras deshacerse de ellos, Peter descubre que Martin Li, uno de los más prominentes filántropos de Nueva York, es quien lidera a los Inner Demons, bajo su alter ego Señor Negativo. Martin al ser director del albergue para desamparados F.E.A.S.T., complicará la vida personal de Peter, ya que su tía May trabaja en dicha institución.',"1681150173.png","59");

    INSERT INTO `Videogames` (title,description,cover,price)
    VALUES ("Spider-man Miles Morales",'La narración continúa desde Marvel's Spider-Man y su contenido descargable The City That Never Sleeps ("La Ciudad Que Nunca Duerme"), durante el cual Miles Morales es mordido por una araña genéticamente mejorada y obtiene poderes similares a los de Peter Parker. Un año después del primer juego y su DLC, Miles se ha integrado completamente en el traje negro y rojo como un experimentado Spider-Man mientras defiende a Nueva York de una guerra de pandillas entre una corporación energética y un ejército criminal de alta tecnología. El nuevo hogar de Miles en Harlem está en el corazón de la batalla. Parker le dice a Miles que tiene que ser como su difunto padre y caminar por el camino para convertirse en un héroe para la ciudad de Nueva York.',"1681150189.png","49");

    INSERT INTO `Videogames` (title,description,cover,price)
    VALUES ("Jedi Survivor",'La historia de Cal Kestis continúa en Star Wars Jedi: Survivor™, un juego galáctico de acción y aventura en tercera persona de Respawn Entertainment, desarrollado en colaboración con Lucasfilm Games. Este título está pensado para jugar en solitario. Su trama se retoma cinco años después de los eventos de Star Wars Jedi: La Orden caída™ y sigue la lucha desesperada de Cal mientras la galaxia está cada vez más dominada por la oscuridad. Cal se encontrará rodeado de amenazas nuevas y conocidas al ser llevado al extremo de la galaxia por el Imperio. Cal, uno de los últimos Caballeros Jedi sobrevivientes, está decidido a oponer resistencia en los tiempos más oscuros de la galaxia, ¿pero hasta dónde está dispuesto a llegar para protegerse a sí mismo, a su equipo y al legado de la Orden Jedi?',"1681150319.png","69");

    INSERT INTO `Videogames` (title,description,cover,price)
    VALUES ("The Last Of Us Part 2",'La historia transcurre cinco años después de los eventos del primer juego. En esta segunda entrega el jugador toma el control de Ellie como la protagonista, la cual emprende un largo viaje para lograr su venganza por el asesinato de Joel.

Por otra parte, también se asume el control de Abby, la deuteragonista del juego, que busca vengar la muerte de su padre, quien resulta ser el cirujano que pretendía operar a Ellie y que fue eliminado por Joel al rescatarla.',"1681150334.png","39");

    INSERT INTO `Videogames` (title,description,cover,price)
    VALUES ("Tom Clancy's Rainbow Six",'El jugador asume el papel de Logan Keller, líder del escuadrón Alpha de Rainbow, que incluye a Gabriel Nowak y Kan Aakashi. La misión inicial de Rainbow es capturar a la terrorista internacional Irena Morales, en una ciudad fronteriza de México. Pero son emboscados por los terroristas y Gabe y Kan son capturados por Irena. Logan logra escapar del incidente junto al equipo de apoyo Joanna Torres y al piloto Brody Lukin, quienes son informados por Six: Ding Chavez, acerca de un problema en las Vegas y tienen que dirigirse ahí. Ya en las Vegas, Logan se reúne con el equipo Bravo de Rainbow en el Strip: Michael Walter y Jung Park. teniendo la misión de rescatar a un asesor de la OTAN, el Doctor Philip Smithy, quien se encuentra cautivo en el casino Calypso',"1681150379.png","19");

    INSERT INTO `Videogames` (title,description,cover,price)
    VALUES ("Tom Raider",'Lara emprende su primera expedición a bordo del "Endurance", con la intención de encontrar el reino perdido de Yamatai. Aunque Whitman está en contra de seguir adelante, la expedición se adentra en el Triángulo del Dragón. El barco es azotado por una tormenta y termina naufragando, dejando a los supervivientes varados en una isla. Lara se separa de los demás al llegar a la orilla y es capturada por un extraño. Ella logra escapar mientras su captor muere cuando la cueva se derrumba. A medida que Lara intenta localizar a los otros supervivientes, encuentra más evidencia de que la isla está habitada, como extrañas esculturas, cadáveres y sacrificios de animales.',"1681150435.png","49");

    INSERT INTO `Videogames` (title,description,cover,price)
    VALUES ("Uncharted 4",'Cronológicamente el juego toma lugar alrededor del año 2014, entre tres y cinco años después de Uncharted 3: La traición de Drake. El retirado cazafortunas Nathan Drake vive felizmente su vida junto con su esposa Elena Fisher, pero todo se derrumba cuando aparece su hermano Sam, el que Nathan pensaba que estaba muerto. Sam necesita su ayuda para desenmascarar una conspiración histórica del famoso pirata aventurero Henry Avery y su legendario tesoro. Además, no son los únicos que buscan el tesoro, ya que Rafe Adler, multimillonario y exsocio de los hermanos Drake mientras estuvieron en una prisión, está buscándolo también, con la ayuda de Nadine Ross, la líder de la red de mercenarios Shoreline. Debido a que Nathan se siente culpable por haber dado por muerto a su hermano en el pasado, decide volver al mundo de los cazatesoros. Durante el viaje, Drake irá por suburbios y zonas cubiertas de nieve, pero la localización principal será Libertalia, una ciudad perdida en Madagascar.',"1681150461.png","49");

    INSERT INTO `Videogames` (title,description,cover,price)
    VALUES ("Watch Dogs Legion",'Watch Dogs: Legion es un videojuego de acción y aventura que se juega desde una perspectiva en tercera persona. El videojuego se desarrolla dentro de un mundo abierto, que es una representación ficticia de la ciudad de Londres, que abarcará hitos notables, municipios y estilos culturales de la ciudad. El mundo del videojuego tiene lugar dentro de un Londres que se ha convertido en un estado de vigilancia perpetua. Las libertades personales han sido muy limitadas, y Albion, una compañía de seguridad privada que actúa como la policía de la ciudad, controla constantemente sus actividades en sus día a día. El jugador tendrá la capacidad de navegar por la ciudad, ya sea a pie, utilizando vehículos, o viajando rápido a través de las estaciones de metro de la ciudad. ',"1681150495.png","59");

    INSERT INTO `Videogames` (title,description,cover,price)
    VALUES ("WWE 2K23",'Al igual que el juego anterior, WWE 2K23 tiene un estilo de juego híbrido entre arcade y simulación. El combate WarGames hará su debut por primera vez en un videojuego de la WWE, este mismo podrá jugarse tanto con luchadores como luchadoras. Los modos de juego confirmados son MyFaction, MyGM, Showcase, MyRise y Creation Suite. 2K Showcase regresó con la superestrella de portada John Cena, lo que permite a los jugadores jugar los momentos más importantes de su carrera en la WWE. ',"1681150530.png","59");

    INSERT INTO `Videogames` (title,description,cover,price)
    VALUES ("The Legend of Zelda",'La trama de The Legend of Zelda es relatada a través del manual de instrucciones y en una pequeña secuencia introductoria antes de la escena donde aparece el título del juego, una vez que el mismo empieza a reproducirse. Un pequeño reino dentro de la tierra de Hyrule el cual es el lugar donde se desarrollan los principales acontecimientos, es asolado por el caos después de que un ejército liderado por Ganon, el Príncipe de la Oscuridad, lo invadiera y robara la Trifuerza del Poder, un fragmento que forma parte de un artefacto mágico capaz de otorgar a su poseedor una poderosa fuerza física.',"1681150752.png","69");

 */