import Table from '@/components/dashboard/Tables';
import AdminNav from '@/components/header/AdminNav'
import Head from 'next/head'

const Dashboard = () => {


    return (
        <>
            <Head>
            <title>Dashboard</title>
            <meta name="description" content="Generated by create next app" />
            <meta name="viewport" content="width=device-width, initial-scale=1" />
            <link rel="icon" href="/gaming.png" />
          </Head>
            <AdminNav/>
            <Table/>
        </>
    )
}

export default Dashboard
