import Head from 'next/head'
import Feed from '@/components/Feed'
import Nav from '@/components/header/Nav'

export default function Home() {
    return (
        <>
            <Head>
            <title>PlayZone</title>
            <meta name="description" content="Generated by create next app" />
            <meta name="viewport" content="width=device-width, initial-scale=1" />
            <link rel="icon" href="/gaming.png" />
          </Head>
                {/*Header  */}
                <Nav></Nav>
                {/* Feed */}         
                <Feed></Feed>
                {/* Feet */}
                

        </>
    )
}
