import LoginPage from '@/components/LoginPage'
import Head from 'next/head'
import React from 'react'

function login() {
    return (
        <>
            <Head>
                <title>Login</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <meta
                    name="viewport"
                    content="width=device-width, initial-scale=1"/>
                <link rel="icon" href="/gaming.png" />
            </Head>
            <LoginPage/>
        </>
    )
}

export default login
