import Login from '@/components/Login'
import Head from 'next/head'
import React from 'react'

function login() {
    return (
        <>
            <Head>
                <title>Login</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <meta
                    name="viewport"
                    content="width=device-width, initial-scale=1"
                />
                <link rel="icon" href="/gaming.png" />
            </Head>
            <div className="w-full h-screen flex items-start">
                <div className="relative w-1/2 h-full sm:flex flex-col hidden">
                    <img
                        className="w-full h-full object-cover"
                        src="https://images.unsplash.com/photo-1579199339853-eec461b791b6?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=930&q=80"
                    />
                </div>
                <div className="sm:relative w-full sm:w-1/2 h-full flex flex-col">
                    <Login />
                </div>
            </div>
        </>
    )
}

export default login
