import SalesCard from '@/components/dashboard/SalesCard'
import AdminNav from '@/components/header/AdminNav'
import Head from 'next/head'
import React from 'react'

function sales() {
  return (
    <>
          <Head>
            <title>PlayZone</title>
            <meta name="description" content="Generated by create next app" />
            <meta name="viewport" content="width=device-width, initial-scale=1" />
            <link rel="icon" href="/gaming.png" />
          </Head>
        <AdminNav/>
        <SalesCard/>
    </>
  )
}

export default sales
