import Footer from '@/components/Footer';
import Head from 'next/head';
import React from 'react'

function Shop() {
  return (
    <>
     <Head>
            <title>Shopping</title>
            <meta name="description" content="Generated by create next app" />
            <meta name="viewport" content="width=device-width, initial-scale=1" />
            <link rel="icon" href="/gaming.png" />
          </Head>
          <Shop/>
          <Footer/>
    </>
  )
}

export default Shop;
